services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - RAILS_MASTER_KEY=644532fa7be4d723aeabfb552cd84759
    volumes:
      - .:/rails
    command: ./bin/rails server -b 0.0.0.0 -p 3000
    stdin_open: true
    tty: true
